config/routes.rb
### == Route Map
### ↓ターミナルに入れるとルーティング情報を書き出す
### bundle exec annotate --routes

#resourcesの中身
#get 'posts'     => 'posts#index'
#post 'posts' => 'posts#create'
#get 'posts/new' => 'posts#new'

#get 'posts/:id/edit' => 'posts#edit'
#get 'posts/:id' => 'posts#show'
#patch 'posts/:id'  => 'posts#update'
#delete 'posts/:id' => 'posts#destroy'


Rails.application.routes.draw do
  # 管理者用 
  # skipオプションでサインインを削除
  devise_for :admin,
    skip: [:registrations, :passwords] ,
    controllers: { sessions: "admin/sessions" }

  # コントローラーの指定
  devise_for :users,
    controllers: { registrations: "public/registrations", sessions: "public/sessions"}

  #ゲストモード用のルーティング
  devise_scope :user do
    post "public/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  #scope moduleでカスタマイズ
  scope module: :public do
    root to:"homes#top"
    get "/about", to: "homes#about"

    #searchのルーティング
    get "/search", to: "searches#search"

    #postと子(commentとfavorite)のルーティング
    resources :posts do
      resources :comments, only: [:create, :destroy]
      resource :favorite, only: [:create, :destroy] #1回しかいいねできないから単数系
    end

    #userとrelationshipのルーティング
    resources :users, only: [:show,:edit,:update, :destroy] do
      get "confirm" => "users#confirm"
      member do
        get :index_favorite
        get :index_follow
     end
      resource :relationships, only: [:create, :destroy]
        get "followings" => "relationships#followings", as: "followings"
        get "followers" => "relationships#followers", as: "followers"
    end
  end

  # namespaceでadminをまとめる
  namespace :admin do
    root to: "users#index"
    get "/search", to: "searches#search"
    resources :users, only: [:show, :index, :destroy] 
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  introduction           :text
#  name                   :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  #active_storage宣言
  has_one_attached :profile_image

  #関連付け
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  #自分がフォローされる（被フォロー）側の関係性
  has_many :followers, through: :reverse_of_relationships, source: :follower
  #被フォロー関係を通じて参照→自分をフォローしている人

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  #自分がフォローする（与フォロー）側の関係性
  has_many :followings, through: :relationships, source: :followed
  #与フォロー関係を通じて参照→自分がフォローしている人

  #バリデーション
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true, presence: true
  validates :introduction, length: { maximum: 50 }

  #ゲストログイン用
  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  # ActiveStorage プロフィール画像
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_icon.jpg'
  end

  #フォローする relationshipコントローラー用
  def follow(user)
    relationships.create(followed_id: user.id)
  end

  #フォローを解除する relationshipコントローラー用
  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

   #指定したユーザーをフォローしているかどうかをinclude？で判定 _btn用
  def following?(user)
    followings.include?(user)
  end

  #検索メソッド実装 LIKEであいまい検索の構文
  def self.looks(word, search)
    search == "partial_match"
    @user = User.where("name LIKE?","%#{word}%")
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  def show
    @user = User.find(params[:id])
  end

  def index 
    @users = User.page(params[:page]).per(3)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path , notice: "アカウント削除に成功しました"
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/index.html.erb
<div class='container'>
  <div class='row'>

    <div class='col-md-3 my-3'><!--サイドバー-->
      <%= render 'layouts/sidebar' %>
    </div>

    <div class='col-md-9'><!--メインコンテンツー-->
      <h2 class="font-weight-bold my-3">
        登録ユーザー一覧
      </h2>
      <table class='table table-hover table-inverse'>
        <% @users.each do |user| %>
          <tr>
            <td> <!--プロフ画像と名前ー-->
              <%= link_to admin_user_path(user) do %>
                <%= image_tag user.get_profile_image, size: '50x50', class:"rounded-circle" %><br>
              <% end %>
              <%= user.name %>
            </td>
            <td><!--自己紹介と登録日-->
              <i class="fa-solid fa-calendar-days " style="color: #2F5E63;"></i>
              <%= user.created_at.strftime('%Y年%m月%d日') %><br>
              <%= user.introduction %>
            </td>
          </tr>
        <% end %>
      </table>
        <%= paginate @users %>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class='container'>
  <div class='row'>

    <div class='col-md-3 my-3'><!--サイドバー-->
      <%= render 'layouts/sidebar' %>
    </div>

    <div class='col-md-9'><!--メインコンテンツー-->
      <h3 class="font-weight-bold my-3">
        <i class="fa-solid fa-user fa-sm" ></i>
        <%= @user.name %> さんの情報
      </h3>

      <div class="row">
        <div class="col-4"><!--プロフ画像と登録日-->
          <%= image_tag @user.get_profile_image, size: '150x150' %><br>
          <i class="fa-solid fa-calendar-days " style="color: #2F5E63;"></i>
          <%= @user.created_at.strftime('%Y年%m月%d日') %><br>
          <p><%= @user.followings.count %>フォロー中</p>
          <p><%= @user.followers.count %>フォロワー</p>
        </div>

        <div class="col-8">
          <div class ="row justify-content-end">
            <%= link_to 'アカウント削除',admin_user_path(@user), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-outline-danger btn-lg " %>
            <div class="py-5">
              <%= @user.introduction %>
            </div>
          </div>

        </div>
      </div>

    </div>

  </div>
</div>