config/routes.rb
### == Route Map
### ↓ターミナルに入れるとルーティング情報を書き出す
### bundle exec annotate --routes

#resourcesの中身
#get 'posts'     => 'posts#index'
#post 'posts' => 'posts#create'
#get 'posts/new' => 'posts#new'

#get 'posts/:id/edit' => 'posts#edit'
#get 'posts/:id' => 'posts#show'
#patch 'posts/:id'  => 'posts#update'
#delete 'posts/:id' => 'posts#destroy'


Rails.application.routes.draw do
  # 管理者用 
  # skipオプションでサインインを削除
  devise_for :admin,
    skip: [:registrations, :passwords] ,
    controllers: { sessions: "admin/sessions" }

  # コントローラーの指定
  devise_for :users,
    controllers: { registrations: "public/registrations", sessions: "public/sessions"}

  #ゲストモード用のルーティング
  devise_scope :user do
    post "public/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  #scope moduleでカスタマイズ
  scope module: :public do
    root to:"homes#top"
    get "/about", to: "homes#about"

    #searchのルーティング
    get "/search", to: "searches#search"

    #postと子(commentとfavorite)のルーティング
    resources :posts do
      resources :comments, only: [:create, :destroy]
      resource :favorite, only: [:create, :destroy] #1回しかいいねできないから単数系
    end

    #userとrelationshipのルーティング
    resources :users, only: [:show,:edit,:update, :destroy] do
      get "confirm" => "users#confirm"
      member do
        get :index_favorite
        get :index_follow
     end
      resource :relationships, only: [:create, :destroy]
        get "followings" => "relationships#followings", as: "followings"
        get "followers" => "relationships#followers", as: "followers"
    end
  end

  # namespaceでadminをまとめる
  namespace :admin do
    root to: "users#index"
    get "/search", to: "searches#search"
    resources :users, only: [:show, :index, :destroy] 
  end
end

app/views/layouts/_btn_index.html.erb
<!--posts/index-->
<!--users/show-->
<%=  link_to index_favorite_user_path(current_user), class:"btn btn-outline-secondary " do %>
  <i class="fa-solid fa-thumbs-up fa-sm "></i>いいねしたポスト
<% end %>

<%=  link_to index_follow_user_path(current_user), class:"btn btn-outline-secondary " do %>
  <i class="fa-solid fa-user-check fa-sm"></i>フォローしているユーザーのポスト
<% end %>

app/views/layouts/_error.html.erb
<!--public/posts/new-->
<!--public/posts/edit-->
<!--public/users/edit-->

<% if obj.errors.any? %>
  <%= obj.errors.count %>件のエラーが発生しました
  <ul>
    <% obj.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-main-color d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
  <div class="container text-center">
    <div class="col md-2">
      <p>© 2025 TEGAKIgram / All rights reserved.</p>
    </div>
  </div>
</footer>

app/views/layouts/_greeting.html.erb
<!--layouts/header-->
<div>
  <% if user_signed_in? %>
    こんにちは <%= current_user.name %> さん!
  <% elsif admin_signed_in? %>
    管理者さんこんにちは!
  <% end %>
</div>

app/views/layouts/_header.html.erb
<header class="bg-main-color d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 ">
  <div class="container py-3 border-bottom">
    <div class ="row">

      <div class="col">
        <%= render 'public/searches/form' %><!--検索-->
      </div>

      <div class ="col text-center"> 
        <%= link_to root_path do %>
          <%= image_tag "logo.jpg", alt: "Logo", width: 50 %>
        <% end %>
        <%= render 'layouts/greeting' %><!--こんにちは-->
      </div>

      <div class ="col ">
        <ul class="nav justify-content-center">

          <% if user_signed_in? %> <!--サインイン時-->
            <li class="nav-item">
              <%= link_to user_path(current_user),class: 'nav-link text-dark' do %>
                プロフィール<i class="fa-solid fa-user fa-xl" style="color: #2F5E63;"></i>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete ,class: 'nav-link text-dark' do %>
                ログアウト<i class="fas fa-sign-out-alt fa-xl" style="color: #2F5E63;"></i>
              <% end %>
            </li>
          <% elsif admin_signed_in? %> <!--Admin時-->
            <li class="nav-item">
              <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' do %>
                ログアウト<i class="fas fa-sign-out-alt fa-xl" style="color: #2F5E63;"></i>
              <% end %>
            </li>

          <% else %> <!--Nobody-->
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: 'nav-link text-dark' do %>
                新規登録<i class="fas fa-user-plus fa-xl" style="color: #2F5E63;"></i>
              <% end %>
            </li>

            <li class="nav-item">
              <%= link_to new_user_session_path,class: 'nav-link text-dark' do %>
                ログイン<i class="fas fa-sign-in-alt fa-xl" style="color: #2F5E63;"></i>
              <% end %>
            </li>
            <%
=begin%>
 <li class="nav-item">
              <%= link_to new_admin_session_path,class: 'nav-link text-dark' do %>
                開発用!管理者ログイン<i class="fas fa-sign-in-alt fa-xl" style="color: #2F5E63;"></i>
              <% end %>
            </li> 
<%
=end%>
          <% end %>
        </ul>
      </div>
  </div>

</div>

</header>

app/views/layouts/_logo.html.erb
<!--view/sessions/new-->
<!--view/registrations/new-->
<!--admin/sessions/new-->
<!--view/homes/about-->
<!--view/homes/about-->
<!--view/users/confirm-->
<%= link_to root_path do %>
  <%= image_tag "logo_text_toka.png", alt: "Logo", width: 200 %>
<% end %>

app/views/layouts/_sidebar.html.erb
<div class="d-flex flex-column bg-light">
  <ul class="nav nav-pills flex-column mb-auto">

    <% if user_signed_in? %> <!--サインイン時-->
      <li class="nav-item">
        <%=  link_to posts_path ,class: 'btn' do %>
          <i class="fa-solid fa-house fa-xl " style="color: #2F5E63;"> ホーム</i>
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to user_path(current_user),class: 'btn' do %>
          <i class="fa-solid fa-user fa-xl " style="color: #2F5E63;"> プロフィール</i>
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to edit_user_path(current_user),class: 'btn' do %>
          <i class="fa-solid fa-gear fa-xl " style="color: #2F5E63;"> 設定</i>
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to new_post_path ,class: 'btn' do %>
          <i class="fa-solid fa-circle-plus fa-xl" style="color: #2F5E63;"> 投稿</i>
        <% end %>
      </li>


 <% else admin_signed_in? %> <!--Admin時-->
      <li class="nav-item">
        <%= link_to admin_root_path,class: 'btn ' do %>
          <i class="fa-solid fa-house fa-xl" style="color: #2F5E63;"></i> 管理者ホーム
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to admin_users_path,class: 'btn ' do %>
          <i class="fa-solid fa-user fa-xl" style="color: #2F5E63;"></i> ユーザー一覧
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to destroy_admin_session_path, method: :delete, class: 'btn' do %>
          <i class="fas fa-sign-out-alt fa-xl" style="color: #2F5E63;"></i> 管理者ログアウト
        <% end %>
      </li> 
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TEGAKIgram</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/cf16111dd4.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %><!--kaminariとflash用-->
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %><!--kaminariとflash用-->
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %><!--bootstrap-->
  </head>


  <body>
    <%= render 'layouts/header' %>
    <!--中身によってnoticeかalertをとりだすeachメソッド-->
    <% flash.each do |message_type, message| %>
      <div class="flash-message <%= message_type %>"><%= message %>
      </div>
    <% end %>

    <main>
      <%= yield %>
    </main>

    <%= render 'layouts/footer' %>
  </body>
</html>